### ISSUE TITLE
Last UEFIFormSet at end of file

### ISSUE THREAD

**Issue by DeathBringer** [LongSoft/Universal-IFR-Extractor#11]
If last **UEFIFormSet** is at the end of the file, then it is considered incorrect and dropped.
This also applies to **UEFIStringPackages**
Replace in file **UEFI.cpp**
 _16) < buffer.size()_
with
 _16) <= buffer.size()_

**Comment by vit9696** [comment]
There are two findings of `16) < buffer.size` in UEFI.cpp, and even if there were less, the description is not clear enough in regards to the bug. Could you provide a test file?

**Comment by DeathBringer** [comment]
Patch two cases.
Attach source (binary) & result (text) file and I'll show you a bug.

**Comment by vit9696** [comment]
I am afraid you forgot to include the attachments.

**Comment by DeathBringer** [comment]
No, I'm waiting attachments from you.

**Comment by vit9696** [comment]
Saw it & fixed.
