### ISSUE TITLE
Crash when parsing vaio insydeh20 SetupUtility

### ISSUE THREAD

**Issue by SquallATF** [LongSoft/Universal-IFR-Extractor#14]
[Section_PE32_image_DriverSampleDxe_SetupUtility_body.zip](https://github.com/LongSoft/Universal-IFR-Extractor/files/2735426/Section_PE32_image_DriverSampleDxe_SetupUtility_body.zip)
here is the SetupUtility dxe.

**Comment by vit9696** [comment]
Also fixed in master, thanks.
