### ISSUE TITLE
cannot normally extract the module

### ISSUE THREAD

**Issue by shikulja** [LongSoft/Universal-IFR-Extractor#15]
MAXIMUS-IX-FORMULA-ASUS-1301.CAP (last)
use this method
https://www.win-raid.com/t3908f16-GUIDE-Grub-Fix-Intel-FPT-Error-BIOS-Lock-Asus-Other-Mod-BIOS-Flash.html

but give wrong txt
```

                                EFI Protocol Detected
--------------------------------------------------------------------------------


                                String Packages
--------------------------------------------------------------------------------
Offset:		Language:
--------------------------------------------------------------------------------
0x6992C		A port. (0x0)


                                   Form Sets
--------------------------------------------------------------------------------
Offset:		Title:
--------------------------------------------------------------------------------


                         Internal Forms Representation
--------------------------------------------------------------------------------
Offset:		Instruction:
--------------------------------------------------------------------------------
```

**Comment by vit9696** [comment]
TL;DR Please upload the efi file you tried to decode and it failed.

**Comment by LSSoniX** [comment]
@vit9696 
Приветствую.
В общем что то не так.
Извлекаем Setup_PE32.
Пропускаем через IFR и вот
https://cloud.mail.ru/public/JMCN/rbF58mPKz

ИФР-Экстрактор 0.3.5

**Comment by vit9696** [comment]
Поправил в 0.3.6, спасибо. На Windows придётся самому собрать, впрочем. Под рукой нету.

**Comment by LSSoniX** [comment]
@vit9696 

Спасибо. :))
Собрал под форточки в VS2013, перекинь в релизы пожалуйста.
https://cloud.mail.ru/public/JMCN/rbF58mPKz

**Comment by vit9696** [comment]
Тебе спасибо. Сделал =)

**Comment by shikulja** [comment]
О, извините поздно увидел. Теперь работает)
