### ISSUE TITLE
malloc: can't allocate region

### ISSUE THREAD

**Issue by cowpod** [LongSoft/Universal-IFR-Extractor#16]
Trying to extract from Setup PE32 image, results in truncated output. Error below.
(There is supposed to be a "CFG Lock" section, but the file ends at "Ref")

> leo@Henrys-MacBook-Pro UEFI % ./ifrextract Setup.efi Setup.txt
> Input: Setup.efi
> Output: Setup.txt
> Protocol: UEFI
> ifrextract(775,0x11d90bdc0) malloc: can't allocate region
> *** mach_vm_map(size=8410472299710251008) failed (error code=3)
> ifrextract(775,0x11d90bdc0) malloc: *** set a breakpoint in malloc_error_break to debug
> leo@Henrys-MacBook-Pro UEFI % 

[Setup.efi.zip](https://github.com/LongSoft/Universal-IFR-Extractor/files/3855392/Setup.efi.zip)
[Setup.txt](https://github.com/LongSoft/Universal-IFR-Extractor/files/3855394/Setup.txt)

**Comment by NikolajSchlej** [comment]
This fork is no longer supported, replaced by [IFRExtractor-RS](https://github.com/LongSoft/IFRExtractor-RS).

**Comment by vit9696** [comment]
@NikolajSchlej from what I remember we do not have feature parity with the other version, so we still have to maintain the two.

**Comment by vit9696** [comment]
Fixed in master.
