### ISSUE TITLE
Protocol: UNKNOWN error: Unknown protocol

### ISSUE THREAD

**Issue by bcdi** [LongSoft/Universal-IFR-Extractor#17]
motherboard: ASUS P8Z77-V LK

```
./ifrextract Setup.bin  Setup.txt
Input: Setup.bin
Output: Setup.txt
Protocol: UNKNOWN
error: Unknown protocol
```

[P8Z77-V-LK-ASUS-1402.zip](https://github.com/LongSoft/Universal-IFR-Extractor/files/4173959/P8Z77-V-LK-ASUS-1402.zip)

[Setup.bin.zip](https://github.com/LongSoft/Universal-IFR-Extractor/files/4173960/Setup.bin.zip)

**Comment by NikolajSchlej** [comment]
There are no IFR string packages in that Setup.bin file, so the result is expected.
The IFR data you seek is in nearby guided section with 97E409E6-4CC1-11D9-81F6-000000000000 GUID.

[IFR.zip](https://github.com/LongSoft/Universal-IFR-Extractor/files/4176470/IFR.zip)

**Comment by SolarTorch** [comment]
> There are no IFR string packages in that Setup.bin file, so the result is expected. The IFR data you seek is in nearby guided section with 97E409E6-4CC1-11D9-81F6-000000000000 GUID.
> 
> [IFR.zip](https://github.com/LongSoft/Universal-IFR-Extractor/files/4176470/IFR.zip)

Hello. Can you clarify how to add the missing IFR string with the specific section pull from the bios file? Thank you so much.
[Section_PE32_image_CORE_DXE_CORE_DXE.bin.zip](https://github.com/LongSoft/Universal-IFR-Extractor/files/7264681/Section_PE32_image_CORE_DXE_CORE_DXE.bin.zip)

**Comment by NikolajSchlej** [comment]
What exactly are you trying to do?

**Comment by SolarTorch** [comment]
> What exactly are you trying to do?

I am trying to find out the cfg lock offset in the bios
