### ISSUE TITLE
Tool wants me to set or reset administrator password

### ISSUE THREAD

**Issue by kasti0** [LongSoft/Universal-IFR-Extractor#19]
When running the command line tool it successfully creates the output .txt file.
However, in that file it says that I have to set or reset my administrator password.
On macOS it also creates the output .txt file but in terminal it says „segmentation fault“ and the actual .txt file stops just after a few lines.
I’ll try to upload both windows and macOS output files.

**Comment by kasti0** [comment]
here both output files with the text about password set/reset.
when I use the GUI version for windows everything works, but I don´t get the "varOffset" values which I need.

[output_macOS.txt](https://github.com/LongSoft/Universal-IFR-Extractor/files/5692281/output_macOS.txt)
[output_Win10.txt](https://github.com/LongSoft/Universal-IFR-Extractor/files/5692284/output_Win10.txt)

**Comment by vit9696** [comment]
It outputs the contents of the Setup file and then crashes. This note is from your firmware. Please upload the .efi file you have. Also try https://github.com/LongSoft/IFRExtractor-RS/releases/tag/v1.0.2 in the meanwhile.

**Comment by kasti0** [comment]
I´m not using an .efi file, I´m using a .ROM file
[(bios.rom.zip)](https://github.com/LongSoft/Universal-IFR-Extractor/files/5694076/bios.rom.zip), which can be extracted without errors with the windows GUI version of ifrextractor.

the Rust version gives me this error when trying to extract:
`Second HII string package of the same language found at offset 0xC12E4
There is no way for this program to determine what package will be used for a given form
Consider splitting the input file`

**Comment by vit9696** [comment]
Please use this version: https://github.com/LongSoft/Universal-IFR-Extractor/releases/tag/0.3.7

**Comment by kasti0** [comment]
thank you for the fast support, now it works!
