### ISSUE TITLE
Crash during text file extraction

### ISSUE THREAD

**Issue by platomav** [LongSoft/Universal-IFR-Extractor#2]
IFR Extractor LS crashes while trying to extract the text file from a [Lenovo Yoga 720-13IKB BIOS](https://pcsupport.lenovo.com/uu/en/products/LAPTOPS-AND-NETBOOKS/YOGA-SERIES/YOGA-720-13IKB-TYPE-81C3/81C3/downloads/DS120622). It seems that only the original IFR Extractor v0.5 works, at some extend, as it manages to extract the txt file before also crashing.

[BIOS_IFR.zip](https://github.com/LongSoft/Universal-IFR-Extractor/files/1579334/BIOS_IFR.zip)

**Comment by Hedova928** [comment]
+1, also having this issue.
