### ISSUE TITLE
Do some entries get lost in conversion?

### ISSUE THREAD

**Issue by BoringBoredom** [LongSoft/Universal-IFR-Extractor#22]
[example BIOS](https://download.asrock.com/BIOS/1200/Z590%20OC%20Formula(1.20)ROM.zip)

searching the entry in UEFITool A58:
![wLJsVPn 1](https://user-images.githubusercontent.com/16615327/127406853-2c244268-9134-4d8f-b7c6-0489334aada9.png)

searching the entry in the .txt file after extraction and conversion of the .sct file with IRFExtractor_0.3.6_win.zip:
![HUqdTpe 1](https://user-images.githubusercontent.com/16615327/127406888-08840880-6348-4fd2-b251-fa8ea69d079d.png)

Most (?) other entries are there (at least I haven't come across other missing ones except this one).

**Comment by NikolajSchlej** [comment]
They are likely not referenced by the forms and entries and only present in strings collection.
