### ISSUE TITLE
Doesn't work on non-Windows systems

### ISSUE THREAD

**Issue by joevt** [LongSoft/Universal-IFR-Extractor#4]
This fork of Universal-IFR-Extractor uses CMake which makes it compilable on unix systems such as macOS.

There are a couple issues:
1. wchar_t is 2 bytes in Windows, but may be 4 bytes in Unix.
- Change wchar_t to char16_t.
- Change wstring to u16string.
- Change wcslen to strlen16. Add the following function:
```
static inline size_t strlen16(register const char16_t * string) {
    if (!string) return 0;
    register size_t len = 0;
    while(string[len++]);
    return len;
}
```

2. _strcmpi is undefined.
- Use strcasecmp instead.

**Comment by NikolajSchlej** [comment]
Fixed in v0.3.3.
