### ISSUE TITLE
Protocol: UNKNOWN problem

### ISSUE THREAD

**Issue by ghost** [LongSoft/Universal-IFR-Extractor#8]
Hello,

thanks for your great work!

On some Gigabyte bioses is problem, they say Protocol: UNKNOWN

Problematic section file attached.

Thanks for fix.

Best

Vaclav

[Section_PE32_image_Setup_Setup_body.efi.zip](https://github.com/LongSoft/Universal-IFR-Extractor/files/2076766/Section_PE32_image_Setup_Setup_body.efi.zip)

**Comment by vit9696** [comment]
The data is not here on some motherboards, but in a separate freeform section.

**Comment by SolarTorch** [comment]
> The data is not here on some motherboards, but in a separate freeform section.

How to deal with this situation?
