### ISSUE TITLE
How to compile??

### ISSUE THREAD

**Issue by davidm71** [LongSoft/Universal-IFR-Extractor#9]
Please point me in the right way to compile IFR Extractor in Windows?

Thanks

**Comment by vit9696** [comment]
Hi,

It is built with CMake. Have a look [on this section of the docs](https://cmake.org/cmake/help/v3.12/manual/cmake-generators.7.html#visual-studio-generators). Most likely on Windows you need something like `cmake -G "Visual Studio 15 2017 Win64"` in the project directory for a Vistual Studio Project to be created.

Vit
